### ISSUE TITLE
PGP Signature invalid

### ISSUE THREAD

**Issue by michaeljwood** [ironrobin/archiso-x13s#10]
It appears the PGP key which signs the linux-x13s and x13s-firmware packages expired.

When trying to install arch using the [EndeavourOS-Tutorial)](https://github.com/ironrobin/archiso-x13s/wiki/EndeavourOS-Tutorial) I received the following errors when trying to use `pacstrap` to bootstrap the system.

```
error: x13s-firmware: signature from "Alex R <alex@ironrobin.net>" is unknown trust
:: File /mnt/var/cache/pacman/x13s-firmware-2024-0513-0-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? (Y/n)
error: linux-x13s: signature from "Alex R <alex@ironrobin.net>" is unknown trust
:: File /mnt/var/cache/pacman/linux-x13s-6.9.2-0-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? (Y/n)
error: failed to commit transaction (invalid or corrupted package)
```

I had set my system to use ntp and ran the ironrobin-setup script to add the key as trusted.

I had also tried to set the date and time manually to a few different times (e.g. 2024-04-30, 2024-05-10, 2024-05-13) to see if that made a difference, but I continue to get the above errors.

**Comment by gian-reto** [comment]
I just did an install today, and it seems like the `ironrobin-setup` script doesn't work correctly, and I ran into the exact same error. If you execute the steps manually, it works (at least it did for me):

```sh
pacman-key --recv-keys 6ED02751500A833A
pacman-key --lsign-key 6ED02751500A833A
```

Remember to add the pacman repo manually as well, as the script usually also does this:

```
[ironrobin-x13s]
Server = https://github.com/ironrobin/x13s-alarm/releases/download/packages
```

Hope it works on your end :+1: 

PS: After following the exact steps from the tutorial, which works without issues, my x13s still doesn't manage to boot though. It gets to `Waiting 10 seconds for device /dev/disk/by-uuid/<uuid>` when I start it and select arch, but drops into an emergency shell (which I'm not able to interact with) as soon as the timeout has elapsed, and to a black screen soon after. I wish you better luck!

**Comment by michaeljwood** [comment]
Ok that's interesting. I get the same thing here when I manually add the keys. The weird thing is I have successfully installed arch and booted using these instructions before. I'm not sure what's changed. The only thing I noticed is the iommu params for grub, but even if I try removing those, I still have the 10 second wait before the black screen.

**Comment by lcassa** [comment]
I'm having the exact same issue, the keys don´t work... I've got no previous experience in building a pacman repo, but perhaps it's a workaround

**Comment by michaeljwood** [comment]
I had some success running the script if I first edit to remove the `--key-server pgp.mit.edu` bit [here](https://github.com/ironrobin/archiso-x13s/blob/aarch64/configs%2Fx13s%2Fairootfs%2Fusr%2Flocal%2Fbin%2Fironrobin-setup#L22). That doesn't help with the system seemingly not able to find the drive and then going all black though.

**Comment by lcassa** [comment]
Unfortunately my attempts didn´t work, I used gh to download the release packages and make a local repo, but its definitely not my area of expertise and although the local repo worked when I run pacstrap it still tries to import the PGP key and fails... ideas?

**Comment by lcassa** [comment]
> Unfortunately my attempts didn´t work, I used gh to download the release packages and make a local repo, but its definitely not my area of expertise and although the local repo worked when I run pacstrap it still tries to import the PGP key and fails... ideas?

Well, I set the pacman.conf for the local repo to `SigLevel = Never` I was able to install, but fell on the same trap you mentioned before, the 10 second and blank screen. Looks like we are all in the same page

**Comment by gian-reto** [comment]
So if you guys boot into the live environment, connect to a network, edit `/etc/pacman.conf` manually to add the repo and execute the two commands to add the keys manually, it fails? This works perfectly on my end... I still haven't found a solution for the problem that it doesn't boot after the install, so I'm not able to help with that. I tried multiple ways (from doing it exactly as described in the wiki to other partitioning setups with and without LUKS, as well as using systemd-boot instead of Grub), but none were successful. I've since moved on to NixOS, which runs surprisingly well on this device.

**Comment by michaeljwood** [comment]
Right, following the commands manually works because it doesn't specify the gpg.mit.edu key server. If you do that or edit the script to remove that parameter before running, you can get all the way through installation. So there's something else going on, but that's far beyond my abilities to solve.

Good to know about Nix. Guess it's a good time to start learning it. Do you happen to know any good guides for getting started with nix on the x13s @gian-reto?

**Comment by michaeljwood** [comment]
I tried installing the mainline kernel from this iso.  I did not add the repo/keys and just install linux instead of linux-x13s.  For good measure I manually copied the dtb to the root of the EFI partition.   I actually managed to get Arch installed and running like this.  However, after logging in in about a minute the screen goes black like with the x13s specific kernel.

**Comment by theironrobin** [comment]
thank you for reporting. i've released a new version of the ISO today that removes the broken MIT keyserver reference. this should fix the OP's issue. If any other issues appear or are still outstanding, feel free to open a new GH issue.

**Comment by gian-reto** [comment]
> Right, following the commands manually works because it doesn't specify the gpg.mit.edu key server. If you do that or edit the script to remove that parameter before running, you can get all the way through installation. So there's something else going on, but that's far beyond my abilities to solve.
> 
> Good to know about Nix. Guess it's a good time to start learning it. Do you happen to know any good guides for getting started with nix on the x13s @gian-reto?

Sorry for the late reply. I basically just read up on the Nix programming language first, which is quite easy to pick up. To learn NixOS and Flakes I consulted the following guide, which is amazing: [https://nixos-and-flakes.thiscute.world](https://nixos-and-flakes.thiscute.world).

To get NixOS running on the X13s, I found a blog post which detailed the installation process here: [https://heywoodlh.io/nixos-thinkpad-x13s](https://heywoodlh.io/nixos-thinkpad-x13s).

I hope that helps!
