### ISSUE TITLE
Restarts after 'loading initial ramdisk'

### ISSUE THREAD

**Issue by takosalad** [ironrobin/archiso-x13s#5]
I chose grub as boot manager.
When I install and then try to boot "Arch Linux", I get:

Booting 'Arch linux'
  Loading Linux linux...
  Loading initial ramdisk...

and then black screen and laptop auto-restarts, for infinite boot loop.

(Side notes about the installation process:
I had to add 2 keys, one from the README (6ED02751500A833A, but had to remove --keyserver or it would hang indefinitely) and 68B3537F39A313B3E574D06777193F152BDBE6A6 to install grub.
Added the ironrobin repo and installed linux-x13s kernel from it, as per README.
Also, the basic pacstrap command from the 'Installation_guide' referred to by the ironrobin distro was not sufficient, instead I had to use the one from https://github.com/ironrobin/archiso-x13s/wiki/EndeavourOS-Tutorial .
I did have to put efi at it's own /boot/efi folder instead of directly into /boot because the EFI partition would not have enough free space to accomodate for the two linux img files that land in /boot on installation. And they have no business there anyway, so I don't really understand why the referred 'Installation_guide' wants users to mount EFI _into_ the existing boot folder, thereby messing everything up, instead of its own /boot/efi folder.)

Could this be the same issue as 'early KMS start' - which supposedly happens with fast SSDs (I have a sabrent 2TB SSD in my x13s):
https://wiki.archlinux.org/title/Kernel_mode_setting#Early_KMS_start
and if so, what would be the name of the graphics driver to include in initramfs?

**Comment by theironrobin** [comment]
does grub find your initrd when you run grub-mkconfig?

**Comment by alexandrtru** [comment]
Hello @theironrobin! thanks for your work!

I have same issue :(

grub-mkconfig outputs looks fine
```
[root@archiso /]# grub-mkconfig -o /boot/grub/grub.cfg
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-linux
Found initrd image: /boot/initramfs-linux.img /boot/initramfs-linux.img
Found fallback initrd image(s) in /boot:  initramfs-linux.img initramfs-linux-fallback.img
Warning: os-prober will not be executed to detect other bootable partitions.
Systems on them will not be added to the GRUB boot configuration.
Check GRUB_DISABLE_OS_PROBER documentation entry.
Adding boot menu entry for UEFI Firmware Settings ...
done
```

**Comment by theironrobin** [comment]
@alexandrtru please post your grub config

**Comment by eholzbach** [comment]
I have the same reboot loop, but I'm trying to use dmcrypt.
Source and generated grub entry.
```
GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet"
GRUB_CMDLINE_LINUX="cryptdevice=/dev/nvme0n1p2:cryptroot root=/dev/mapper/cryptroot efi=noruntime"
```
```
menuentry 'Arch Linux' --class arch --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-e1999382-6350-4946-978b-8907abf0213d' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod fat
	search --no-floppy --fs-uuid --set=root 4186-339F
	echo	'Loading Linux linux ...'
	linux	/vmlinuz-linux root=UUID=e1999382-6350-4946-978b-8907abf0213d rw cryptdevice=/dev/nvme0n1p2:cryptroot root=/dev/mapper/cryptroot efi=noruntime loglevel=3 quiet

	echo	'Loading initial ramdisk ...'
	initrd	/initramfs-linux.img
}
```
fstab
```
# /dev/mapper/cryptroot
UUID=e1999382-6350-4946-978b-8907abf0213d	/         	ext4      	rw,relatime	0 1

# /dev/nvme0n1p1
UUID=4186-339F      	/boot     	vfat      	rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro	0 2
```

blkid
```
/dev/nvme0n1p1: UUID="4186-339F" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="5e8fdcc4-e0c9-4019-b975-08c306d4ae8a"
/dev/nvme0n1p2: UUID="08531938-db36-4f93-9e62-10b5b37ca303" TYPE="crypto_LUKS" PARTUUID="618d89c4-bb51-462e-933e-36842795d7e0"
/dev/mapper/cryptroot: UUID="e1999382-6350-4946-978b-8907abf0213d" BLOCK_SIZE="4096" TYPE="ext4"
```
mkinitcpio hooks
```
HOOKS=(base udev autodetect modconf block filesystems keyboard keymap encrypt fsck)
```

**Comment by theironrobin** [comment]
can everyone please retry with the latest kernel, 6.5.0-0-x13s+?

**Comment by eholzbach** [comment]
Purged the drive. Fresh install on 6.5. Same results.

**Comment by alexandrtru** [comment]
Hello! 

I'm successfully booted at 6.5-rc7 kernel, when manually added `devicetree <path/to/dtb>/sc8280xp-lenovo-thinkpad-x13s.dtb` record in my `grub.cfg`

**Comment by theironrobin** [comment]
@eholzbach , can you try alexandrtru's fix?

**Comment by eholzbach** [comment]
Adding the devicetree setting to grub gets me out of the reboot loop. After it prints the message loading initial ramdisk, I see a cursor blink twice then the screen goes black. After a minute or so the screen flickers once. It stays this way until I reboot the machine. I do have mesa installed from your repo.

I configured the network and ssh to come up on boot, but it never connects.

**Comment by theironrobin** [comment]
@eholzbach I think your issue is now due to having the wrong modules in your initrd because you enabled FDE. Please see this section: https://github.com/ironrobin/archiso-x13s/wiki/Feature-Support#full-disk-encryption then run mkinitcpio -P

This should be a separate issue so if you keep having FDE problems after doing the fix I linked, then you will need to open a new issue.
