### ISSUE TITLE
systemd-boot fails to load the linux-x13s kernel

### ISSUE THREAD

**Issue by luluco250** [ironrobin/archiso-x13s#7]
I have followed the instructions to add the ironrobin-x13s repository, installed a barebones system with systemd-boot, using the recommended kernel parameters + the dtb option used by Debian and archiso-x13s.

I have tried both `linux-x13s` and `linux-x13s-rc`, but both result in the following error when loading from systemd-boot:
`Error loading \vmlinuz-linux: Unsupported`

I have also tried using EFISTUB by adding an entry that boots the kernel directly, but when trying to load it from the boot menu I get immediately kicked back to the menu.

Am I missing something? I have also tried booting with no kernel parameters, it seems like the kernel itself is broken somehow? Very odd because the archiso kernel boots fine.

I should mention that systemd-boot is able to load Windows 11, so it doesn't seem to be a problem with the bootloader.

**Comment by PMaynard** [comment]
I too had a issues with systemd-boot. I ended up using grub, following the arch wiki and the kernel booted up fine. 

This wiki entry should help you: https://github.com/ironrobin/archiso-x13s/wiki/EndeavourOS-Tutorial

**Comment by luluco250** [comment]
I guess I'll try Grub, though it's weird that would be an issue since archiso-x13s uses systemd-boot.

Update: Grub works, editing issue to reflect this.

**Comment by theironrobin** [comment]
this has to do with systemd-boot issue (https://github.com/systemd/systemd/issues/23788). nothing i can fix, sorry. But with linux-x13s kernel I do ship the uncompressed kernel (vmlinux) as well so you can make systemd-boot look for that instead as a workaround!
