### ISSUE TITLE
Where can I access current battery state?

### ISSUE THREAD

**Issue by chknlittle** [ironrobin/archiso-x13s#8]
I want to access current battery state so i can show it in my i3status bar.

I'm seeing this folder

```
$ ls /sys/class/power_supply/

qcom-battmgr-ac  qcom-battmgr-bat  qcom-battmgr-usb  qcom-battmgr-wls
```

 but It's not obvious to me how I can get what I'm looking for from here

**Comment by PMaynard** [comment]
While not a direct answer to your question, you may use the following:

`upower -i /org/freedesktop/UPower/devices/battery_qcom_battmgr_bat`

This shows the battery information, and to extract just the percent remaining you may use: 

`bat_percent=$(upower -i /org/freedesktop/UPower/devices/battery_qcom_battmgr_bat|grep percentage|grep -o "[0-9.]*" | cut -d '.' -f1 )`

**Comment by chknlittle** [comment]
thank you for that command, it works for me but the values inside don't seem reasonable.

I'm posting from the x13s without a charger connected and this is the output of the file currently

```
$ upower -i /org/freedesktop/UPower/devices/battery_qcom_battmgr_bat

  native-path:          qcom-battmgr-bat
  power supply:         yes
  updated:              Thu 07 Dec 2023 02:01:23 PM CET (3 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               unknown
    warning-level:       none
    energy:              0 Wh
    energy-empty:        0 Wh
    energy-full:         0 Wh
    energy-full-design:  0 Wh
    energy-rate:         0 W
    charge-cycles:       N/A
    percentage:          0%
    icon-name:          'battery-missing-symbolic'
  History (charge):
    1701954068	0.000	unknown
  History (rate):
    1701954068	0.000	unknown
```

I have a feeling this may have something to do with the kernel options? Or maybe it's because I removed a couple to see if it impacted behavior? I suppose I could add them back? :thinking:

**Comment by PMaynard** [comment]
Yes. Fully charged, and plugged in, my output looks like this: 

```
[freethink@x13s ~]$ upower -i /org/freedesktop/UPower/devices/battery_qcom_battmgr_bat
  native-path:          qcom-battmgr-bat
  vendor:               Sunwoda
  model:                LNV-5B10W51880
  serial:               580
  power supply:         yes
  updated:              Thu 07 Dec 2023 15:53:49 GMT (27 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    energy:              49.99 Wh
    energy-empty:        0 Wh
    energy-full:         49.99 Wh
    energy-full-design:  49.5 Wh
    energy-rate:         0 W
    voltage:             8.721 V
    charge-cycles:       23
    percentage:          100%
    temperature:         29.7 degrees C
    capacity:            100%
    technology:          lithium-ion
    icon-name:          'battery-full-charged-symbolic'
  History (rate):
    1701964429	0.000	fully-charged
    1701964399	1.123	fully-charged
    1701964368	1.646	fully-charged
```

For the battery, as detailed in the wiki [1](https://github.com/ironrobin/archiso-x13s/wiki/Feature-Support#power) you'll need the following installed: 

* https://aur.archlinux.org/packages/qrtr-git
* https://aur.archlinux.org/packages/pd-mapper-git 

My kernel parameters are, the last one is meant to improve power usage for PCIe as detailed [here](https://wiki.debian.org/InstallingDebianOn/Thinkpad/X13s#USB_throughput_and_PCIe_ASPM): 

```
efi=noruntime pd_ignore_unused clk_ignore_unused iommu.passthrough=0 iommu.strict=0 pcie_aspm.policy=powersupersave
```

**Comment by chknlittle** [comment]
Ok I installed those two packages using yay and matched your kernel params to mine

Still getting back 0 when using the upower command

Any other suggestions as to what I can look into to get this to work? Do you think the specific version of my device has any bearing on this?

**Comment by chknlittle** [comment]
nvm! I followed the link to the wiki as suggested and saw I also had to enable the installed service 

```
sudo systemctl enable --now pd-mapper
```

Battery information coming back for me now.

Thanks for the optimization also, this battery life looks incredible :rocket:

**Comment by chknlittle** [comment]
fwiw this is how I display the battery % and time using i3status-rust

```
block = "battery"
format = " $percentage {$time |}"
device = "DisplayDevice"
driver = "upower"
```
