### ISSUE TITLE
Setting up audio

### ISSUE THREAD

**Issue by chknlittle** [ironrobin/archiso-x13s#9]
How can I set up audio?

Currently I have alsa and pulse installed but when I check pavucontrol it just shows a null device. The same goes for earphones when I plug them into the audio jack.

**Comment by PMaynard** [comment]
Checkout the wiki:

https://github.com/ironrobin/archiso-x13s/wiki/Feature-Support#audio

I have not been able to get the speakers or aux cable audio working. Only USB/Bluetooth audio has worked for me.

**Comment by chknlittle** [comment]
That'll do for me, thanks!

**Comment by chknlittle** [comment]
Interestingly enough I have sound through my speakers. Haven't tested my audio jack yet but somewhere along the way it started working?

Not sure about reproducing but this problem is solved for me
